### ISSUE TITLE
Ничего себе

### ISSUE THREAD

**Issue by ariran5** [aleha84/simple.canvas.core2#1]
Ты наделал демок )

**Comment by aleha84** [comment]
Не хочу останавливаться.

**Comment by ariran5** [comment]
Новые крутые) Ты рисуешь в редакторе или из головы в прямом эфире ?

**Comment by aleha84** [comment]
всё в рантайме ))) 
Для реально художественных вещей, я разработал свой маленький онлайн редактор, который возвращает json модель, которая в свою очередь рендерится на лету в сцене.
